### ISSUE TITLE
Store and Store Tree creation

### ISSUE THREAD

**Issue by mtmr0x** [mtmr0x/nucleo#1]
## Description

It must create the [storeTree](https://github.com/mtmr0x/nucleo/wiki/storeTree) and the store objects.

## Tasks

- [x] `storeTree` architecture;
- [x] save `storeTree` in memory;
- [x] `store` architecture;
- [x] save `store` in memory
- [x] Have a consultable function for the store || or store only inside the dispatcher function scope?
- [x] Subscribe listener to the store events update

## Questions

- Do store start without its contracts if not provided initial state?
