### ISSUE TITLE
Improve NucleoList type tests

### ISSUE THREAD

**Issue by mtmr0x** [mtmr0x/nucleo#16]
## Task
Improve `NucleoList` tests, exploring possible flaws using `update` method

### flaws tests
- [x] try to `update` a list with primitive values
- [x] try to `update` a list with NucleoObject values
- [x] try to `update` values to a list not according to the list primitive type expected
- [x] try to `update` values to a list not according to its expected NucleoObject type
