### ISSUE TITLE
NucleoObjectType

### ISSUE THREAD

**Issue by mtmr0x** [mtmr0x/nucleo#4]
# Task 
Every object in Nucleo must be a Nucleo Object Type.

# Checklist
- [x] Create class to instance objects
- [x] Make store creation validate every object as `NucleoObjectType`
- [x] Lawyer must understand instances of `NucleoObjectType`
