### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by mtmr0x** [mtmr0x/nucleo#5]
## Task

Contract is the Object Model for creating `NucleoObject`s. Creating the store, every object passed must be a valid contract created with `NucleoObject`;

## Checklist

- [x] Contracts must be passed as Objects;
- [x] Contracts must have exclusive names. This must not be allowed to create 2 contracts with the same name;
- [x] Creating store, the contracts must be validated if it's `instanceof` `NucleoObject`;

## Tests

- [x] You can't create two contracts with the same name per store
- [x] Every contract must be instance of `NucleoObject`
- [x] Creating the store and generating contracts, `dispatch` and `subscribe` must be returned
